language: node_js
node_js:
- node
env:
  global:
    secure: Ji9kHPJgFX7b3vGhkOuBcn7xIWJLilvZ7phIvjepb3RuAsBnXaMTROINMc0I7LsEyS8A8NWKKnj1yXJ5pi79PS2R1fBD+tlumryqB8moNWZObMC8bImIuakeUnMST5UD6lqDc5x8bi6Klpjs5Gr6vNoI7u8GCv3KK8xMGLfTraQFTR2tGthJNNSHNTdW1cmuoa2cgC/dZmfKo9HVTajzmwxNPsmMsgZFgDIzCJQaKSyZFEFt6m1PzbiYehEafMJiDny1+kmgGoiOchJjSn7JekvQb6w11VMTfSMd8E7NSUeXe3/b+W5sFdL+gT/zhiZ+J6SFQqZ4RqBBcuKKehTevr8e62fBYY+40awTHk/drnRFrKBWYHHUVuqJYM6U7dayRdLHKy++UwtaZUlKbP7itSETDyaVt+GmUFd6rwh8e+Xf1ZcM0MmNAubNbfwl29nWOYAqlHOUQkAID4gVy3wew/XA5EsYwjlgzSBTTUf1+bJm3vApK87FAaAv8lglryG5FyQZHKL0k7HpPhqB2jSQyRyPpcKmED95SyIbuFoM5auyCGMwoabomievVWdyXb6U12ejRtgFc3tD4zSBpluoxfDeKDmTCrBHuTsxrfNOWN9+tQ4EfWNTB+RIqr2SpyWU5f08hwqtxbecWQuatPwo6hKaoXFZ2SgLOtCMI58tzFA=
deploy:
  matrix:
  - skip_cleanup: true
    provider: script
    script: npm run build && npm run gh-pages
    on:
      branch: master
  - skip_cleanup: true
    provider: script
    script: npm run build && npm run gh-pages -- -p "$TRAVIS_BRANCH"
    on:
      all_branches: true
      condition: '"$TRAVIS_BRANCH" != "master" && "$TRAVIS_BRANCH" != "gh-pages"'
  api-key:
    secure: s3knHPit3ycW+PkYt7Jh83gKTfNGZD4Ian5qiMrtZVyHeGnzBvkb4peq0gV0EqhR4/zyfZKLJqxbC1EVz1Sp7+RR3hCkn3NAo2Be83mF2XtVSW98GTcpKnmxA7u/x0vKmLKxPtYwkyuXpCfxUU2OvRXdo+UdjdNY1zo9ht4pOP2wjFdCutuZE2U5AxlMO58ycAvyaqlWob8+e5iZ+IdM6uVz1EZnPE5Qa6tJQ2qZiQLohmxZdJyJ0d2WrldDUwxb4sb4ttX4JNhS8izMpZ/LTZSR4wkqWn8EKitib6PZh8soB+p//TWMlPIqcLRRZBOgZXg0KxC50tE8uP6MVhmTs08Ud5wsLrLncufyg6J2Tf7v6nI0fY/SfchYlGp5+jLQ16/9DUH5UyT+CLvAQ4V4scK948iemSGzWFPA7+2I3jjMkct4Pf0HTbhUUObauOoAXoOBaGlTZVct9oNgK1iE0Y/U68W+kMi1vs9pYLtaG/VpOLk8bRxQxIASoJUbo5bBShsdpZFgNfhV2sJslHl//KZRhHryPpgPoayXJYgj6dfFBmt63NpuOsdYHx0GANmZ75IuSiLhaa+8hfa02gNkJ/AeGhEx8hrqIb9aJK992MnUtH/+WcygBap09qKhCc1706+tbbD83fjJjGN3hsX75HSdgYwFdDWuye+zTll8e/Q=
