language: node_js
node_js:
- node
env:
  global:
    secure: Ji9kHPJgFX7b3vGhkOuBcn7xIWJLilvZ7phIvjepb3RuAsBnXaMTROINMc0I7LsEyS8A8NWKKnj1yXJ5pi79PS2R1fBD+tlumryqB8moNWZObMC8bImIuakeUnMST5UD6lqDc5x8bi6Klpjs5Gr6vNoI7u8GCv3KK8xMGLfTraQFTR2tGthJNNSHNTdW1cmuoa2cgC/dZmfKo9HVTajzmwxNPsmMsgZFgDIzCJQaKSyZFEFt6m1PzbiYehEafMJiDny1+kmgGoiOchJjSn7JekvQb6w11VMTfSMd8E7NSUeXe3/b+W5sFdL+gT/zhiZ+J6SFQqZ4RqBBcuKKehTevr8e62fBYY+40awTHk/drnRFrKBWYHHUVuqJYM6U7dayRdLHKy++UwtaZUlKbP7itSETDyaVt+GmUFd6rwh8e+Xf1ZcM0MmNAubNbfwl29nWOYAqlHOUQkAID4gVy3wew/XA5EsYwjlgzSBTTUf1+bJm3vApK87FAaAv8lglryG5FyQZHKL0k7HpPhqB2jSQyRyPpcKmED95SyIbuFoM5auyCGMwoabomievVWdyXb6U12ejRtgFc3tD4zSBpluoxfDeKDmTCrBHuTsxrfNOWN9+tQ4EfWNTB+RIqr2SpyWU5f08hwqtxbecWQuatPwo6hKaoXFZ2SgLOtCMI58tzFA=
deploy:
- skip_cleanup: true
  provider: script
  script: npm run build && npm run gh-pages
  on:
    branch: master
- skip_cleanup: true
  provider: script
  script: npm run build && npm run gh-pages -- -p "$TRAVIS_BRANCH"
  on:
    all_branches: true
    condition: '"$TRAVIS_BRANCH" != "master" && "$TRAVIS_BRANCH" != "gh-pages"'
